-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bet_result
(
    game_id integer NOT NULL,
    result_id integer NOT NULL,
    date_id integer NOT NULL,
    home_team_id integer NOT NULL,
    away_team_id integer NOT NULL,
    number_of_bets integer NOT NULL,
    income integer NOT NULL,
    outcome integer NOT NULL,
    bet_result integer NOT NULL,
    coef double precision NOT NULL,
    CONSTRAINT bet_result_pkey PRIMARY KEY (game_id, result_id, home_team_id, away_team_id, date_id)
);

CREATE TABLE IF NOT EXISTS public.team
(
    id integer NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    location_id integer,
    CONSTRAINT team_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.location
(
    id integer NOT NULL DEFAULT nextval('location_id_seq'::regclass),
    city character varying(100) COLLATE pg_catalog."default",
    state character varying(100) COLLATE pg_catalog."default",
    country character varying(50) COLLATE pg_catalog."default" DEFAULT 'Germany'::character varying,
    CONSTRAINT location_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.player
(
    id integer NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default",
    age integer NOT NULL,
    nationality character varying(50) COLLATE pg_catalog."default" NOT NULL,
    team_id integer,
    CONSTRAINT player_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.player_result
(
    game_id integer NOT NULL,
    player_id integer NOT NULL,
    date_id integer NOT NULL,
    goals integer NOT NULL,
    assists integer NOT NULL,
    fouls integer NOT NULL,
    "time" integer NOT NULL,
    CONSTRAINT player_result_pkey PRIMARY KEY (game_id, player_id, date_id)
);

CREATE TABLE IF NOT EXISTS public.date
(
    id integer NOT NULL DEFAULT nextval('date_id_seq'::regclass),
    day date,
    month integer,
    year integer,
    day_of_week character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT date_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.game
(
    id integer NOT NULL,
    league_id integer,
    venue_id integer,
    home_team_id integer,
    away_team_id integer,
    date_id integer,
    CONSTRAINT game_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.league
(
    id integer NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    season integer NOT NULL,
    round character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT league_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.venue
(
    id integer NOT NULL,
    city character varying(50) COLLATE pg_catalog."default",
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT venue_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.game_result
(
    game_id integer NOT NULL,
    period_id integer NOT NULL,
    date_id integer NOT NULL,
    team_id integer NOT NULL,
    goals integer NOT NULL,
    assists integer NOT NULL,
    fouls integer NOT NULL,
    red_cards integer NOT NULL,
    yellow_cards integer NOT NULL,
    substitutions integer NOT NULL,
    CONSTRAINT game_result_pkey PRIMARY KEY (game_id, period_id, team_id, date_id)
);

CREATE TABLE IF NOT EXISTS public.period
(
    id integer NOT NULL DEFAULT nextval('period_id_seq'::regclass),
    period_name character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT period_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.result
(
    id integer NOT NULL DEFAULT nextval('result_id_seq'::regclass),
    name character varying(20) COLLATE pg_catalog."default",
    score character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT result_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.bet_result
    ADD CONSTRAINT fk_away_team FOREIGN KEY (away_team_id)
    REFERENCES public.team (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bet_result
    ADD CONSTRAINT fk_date FOREIGN KEY (date_id)
    REFERENCES public.date (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bet_result
    ADD CONSTRAINT fk_game FOREIGN KEY (game_id)
    REFERENCES public.game (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bet_result
    ADD CONSTRAINT fk_home_team FOREIGN KEY (home_team_id)
    REFERENCES public.team (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bet_result
    ADD CONSTRAINT fk_result FOREIGN KEY (result_id)
    REFERENCES public.result (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.team
    ADD CONSTRAINT fk_location FOREIGN KEY (location_id)
    REFERENCES public.location (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.player
    ADD CONSTRAINT fk_team FOREIGN KEY (team_id)
    REFERENCES public.team (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.player_result
    ADD CONSTRAINT fk_date FOREIGN KEY (date_id)
    REFERENCES public.date (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.player_result
    ADD CONSTRAINT fk_game FOREIGN KEY (game_id)
    REFERENCES public.game (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.player_result
    ADD CONSTRAINT fk_player FOREIGN KEY (player_id)
    REFERENCES public.player (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_player_result_player_id
    ON public.player_result(player_id);


ALTER TABLE IF EXISTS public.game
    ADD CONSTRAINT fk_away_team FOREIGN KEY (away_team_id)
    REFERENCES public.team (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.game
    ADD CONSTRAINT fk_date FOREIGN KEY (date_id)
    REFERENCES public.date (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.game
    ADD CONSTRAINT fk_home_team FOREIGN KEY (home_team_id)
    REFERENCES public.team (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.game
    ADD CONSTRAINT fk_league FOREIGN KEY (league_id)
    REFERENCES public.league (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_game_league_id
    ON public.game(league_id);


ALTER TABLE IF EXISTS public.game
    ADD CONSTRAINT fk_venue FOREIGN KEY (venue_id)
    REFERENCES public.venue (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.game_result
    ADD CONSTRAINT fk_date FOREIGN KEY (date_id)
    REFERENCES public.date (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.game_result
    ADD CONSTRAINT fk_game FOREIGN KEY (game_id)
    REFERENCES public.game (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.game_result
    ADD CONSTRAINT fk_period FOREIGN KEY (period_id)
    REFERENCES public.period (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.game_result
    ADD CONSTRAINT fk_team FOREIGN KEY (team_id)
    REFERENCES public.team (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;